- name: "Container for app"
  docker_container:
    name: "app1"
    image: "{{docker_repo}}/image_name"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{docker_network_name}}"
    tags:
    - deploy
    - deploy_app1

  