- name: "Container for {{image_name}}"
  docker_container:
    name: "{{image_name}}"
    image: "{{docker_repo}}/{{image_name}}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{docker_network_name}}"


  