- name: ensure nginx conf directory
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: copy main nginx conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Run nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - IP:80:80
      - 8.8.8.8:443:443
      - 0.0.0.0:700000:653
    restart_policy: unless-stopped
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
